<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-4UBCD2HL" failures="1" tests="1" name="organization.CreateContactWithSupportDateTest" time="20.918" errors="0" timestamp="2025-04-10T15:28:38 IST" skipped="0">
  <testcase classname="organization.CreateContactWithSupportDateTest" name="CreateContactTest" time="20.918">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at organization.CreateContactWithSupportDateTest.CreateContactTest(CreateContactWithSupportDateTest.java:149)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[CreateContactTest----started--
CreateContactTest--failed--]]>
    </system-out>
  </testcase> <!-- CreateContactTest -->
  <system-out>
    <![CDATA[report configuration
configure the DB:connect
BT:parallel Exe
launch the browser
login to application
createorganizationTest----started--
createorganizationTest--succes--
logout to application
close the browser
launch the browser
login to application
CreateOrganizationTest----started--
CreateOrganizationTest--succes--
logout to application
close the browser
launch the browser
login to application
createorganizationTest----started--
createorganizationTest--succes--
logout to application
close the browser
launch the browser
login to application
createorgaWithIndustryTest----started--
createorgaWithIndustryTest--succes--
logout to application
close the browser
launch the browser
login to application
CreateContactTest----started--
CreateContactTest--failed--
logout to application
close the browser
launch the browser
login to application
CreateContact_OrgnameTest----started--
CreateContact_OrgnameTest--succes--
logout to application
close the browser
launch the browser
login to application
Create_Contact_Test----started--
Create_Contact_Test--succes--
logout to application
close the browser
launch the browser
login to application
createorgaWithIndustryTest----started--
createorgaWithIndustryTest--succes--
logout to application
close the browser
launch the browser
login to application
Create_Contact_Test----started--
Create_Contact_Test--succes--
logout to application
close the browser
launch the browser
login to application
CreateContact_OrgnameTest----started--
CreateContact_OrgnameTest--succes--
logout to application
close the browser
launch the browser
login to application
CreateContactTest----started--
CreateContactTest--failed--
logout to application
close the browser
launch the browser
login to application
CreateOrganizationTest----started--
CreateOrganizationTest--failed--
logout to application
close the browser
AT:parallel Exe
close the db connection]]>
  </system-out>
</testsuite> <!-- organization.CreateContactWithSupportDateTest -->
